### PR TITLE
Add CI settings

### PR DESCRIPTION
**Pull request by okkez**
Use stub responses to setup CI.

### CODE REVIEW

**Comment by okkez** [comment]
Finish adding CI settings.
But I don't add tests using stub responses for output plugin.
If we use stub responses for output plugin tests, we cannot assert stored events on cloudwatch(AWS).
Does it make sense that we use stub responses to test output plugin?

**Comment by cosmo0920** [comment]
Oops, this PR got conflict due to merging #148.
Could you resolve conflict?
After resolving conflict, I'll merge this PR. :smile:

**Comment by okkez** [comment]
Resolved conflicts.

**Comment by okkez** [comment]
I prefer another PR.

**Comment by cosmo0920** [comment]
OK. Let's merge this PR.

**Pull request merged**
