### PR TITLE
cloudwatch input InvalidParameterException fix and use_todays_log_stream param

### PR DESCRIPTION
**Pull request by barrytam20**
- fix to issue #116 by adding condition to check if next token is empty before sending

- added condition to check if next token changed before serializing it

- added `use_todays_log_stream` option to use todays date as log stream name prefix (`YYYY/MM/DD`). This is useful for pulling logs created by lambdas

### CODE REVIEW

**Comment by sampointer** [comment]
Hey. Author of https://github.com/sampointer/fluent-plugin-cloudwatch-ingest/ here. Relying on the presumption that log from a given day will begin to go into a newly-prefixed log group is dangerous and incorrect.

Lambdas can persist for 5-8 hours, and can continuing writing to the "old" log group for that period of time. You *will* miss logs from any reasonably trafficked lambda with this method.

**Comment by barrytam20** [comment]
hey @sampointer i was aware of this issue, but i didnt think lambda would write to a log stream 5 hours old. 

i think a simple fix might be to run `describe_log_streams` for today's date and yesterdays

**Comment by sampointer** [comment]
Hey Barry. I've seen it and have telemetry to show it.

Whilst I was using my plugins I was pulling about 20K/s of logging through
a fluentd infrastructure, about 50% of which was specifically
lambda-generated Cloudwatch logs.

It was a perennial problem on hot lambdas and one of many reasons I
abandoned my plugins for log subscriptions.

**Comment by barrytam20** [comment]
pushed some code to also process yesterday's logs to cover edge case pointed out by @sampointer

**Pull request merged**
